site_name: MOSFIRE DRP Documentation
theme: readthedocs
pages:
    - 'Home': index.md
    - 'DRP Manual':
        - 'Contents': manual.md
        - 'Changes': changes.md
        - 'Preface': preface.md
        - 'Installing': installing.md
        - 'Retrieve Your Data': retrieve.md
        - 'Handle': handle.md
        - 'Automatic Generation of the Driver File': autodriver.md
        - 'The driver.py File': driver.md
        - 'Flats': flats.md
        - 'Wavelength Calibration – Y, J, and H Bands': wavelengthYJH.md
        - 'Wavelength Calibration – K Band': wavelengthK.md
        - 'Background Subtraction': background.md
        - 'Rectify': rectify.md
        - 'Spectral Extraction': extract.md
        - 'Long2pos Reductions': long2pos.md
        - 'Longslit Reductions': longslit.md
        - 'A Word About Header Comments': headercomments.md
        - 'Some Hints': hints.md
