#!/bin/csh -f

# INSTRCUCTIONS. Edit the 

if ($#argv == 0) then
        echo "Starting MOSFIRE Python"
        ipython --pylab --colors Linux
else
    switch ( $argv[1] )
        case "libs":
            python -c "import sys; print sys.path"
            breaksw

        case "db":
            mospy_db.py $*
            breaksw

        case "handle":
            mospy_handle.py $*
            breaksw

        case "what":
            mospy_what.py $*
            breaksw

        default
            python $*
            breaksw
    endsw
endif

onintr -

    
