#!/bin/csh -f

# INSTRCUCTIONS. Edit the 

# 1. Update the full path to the Ureka install for the two aliases
# below
#alias ur_setup 'eval `/Users/lrizzi/.ureka/ur_setup -csh \!*`'
#alias ur_forget 'eval `/Users/lrizzi/.ureka/ur_forget -csh \!*`'



# If pythonpath is not previously defined, define it so that 
#   the setenv works below..
if (! $?PYTHONPATH ) setenv PYTHONPATH 


# 2. Set MOSPATH to the full path to the MOSFIRE DRP code repository
# example:
# Change /scr2/mosfire/DRP/mosfire to /Users/myname/MOSFIRE/DRP
setenv MOSPATH /Users/lrizzi/MosfireDRP
setenv PYTHONPATH ${PYTHONPATH}:${MOSPATH}

if (! -d $MOSPATH) then
    echo "Path '$MOSPATH' does not exist. Modify $0"
    echo "and change MOSPATH to the DRP directory."
    exit 1
endif

setenv MYPYTHON "/Users/lrizzi/anaconda/bin/python"
setenv MYIPYTHON "/Users/lrizzi/anaconda/bin/ipython"

if ($#argv == 0) then
        echo "Starting MOSFIRE Python"
        $MYIPYTHON --pylab --colors Linux
else
    switch ( $argv[1] )
        case "libs":
            $MYPYTHON -c "import sys; print sys.path"
            breaksw

        case "db":
            $MYPYTHON ${MOSPATH}/apps/db.py $*
            breaksw

        case "handle":
            $MYPYTHON ${MOSPATH}/apps/handle.py $*
            breaksw

        case "AutoDriver":
            $MYPYTHON ${MOSPATH}/apps/AutoDriver.py $*
            breaksw

        case "what":
            $MYPYTHON ${MOSPATH}/apps/what.py $*
            breaksw

        default
            $MYPYTHON $*
            breaksw
    endsw
endif

onintr -

    
